# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Climate Change Uncertainty Spillover in the Macroeconomy
author: Suri Chen
logo: mfr.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
only_build_toc_files: true
execute:
  execute_notebooks: "cache"
  timeout: 600

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - climate.bib

# Information about where the book exists on the web
repository:
  url                       : https://github.com/lphansen/ClimateUncertaintySpillover  # The URL to your book's repository
  path_to_book              : "jybook"  # A path to your book's folder, relative to the repository root.
  branch                    : macroAnnual_v2  # Which branch of the repository should be used when creating links

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false

sphinx:
  extra_extensions: 
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
